{% set name = "shap" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a53901fc44396d92a12b985d83ca4a47a7dcc4a04a7f7e556232a35f17d30c8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]
  ignore_run_exports:
    - numpy

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - numpy {{ numpy }}
    - cython >=3.0.11
    - packaging >=20.9
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - pandas
    - tqdm >=4.27.0
    - packaging >20.9
    - slicer 0.0.8
    - numba >=0.54
    - cloudpickle
    - typing-extensions
  run_constrained:
    # scaled_dot_product_attention attribute is only available
    # with a newer version of pytorch (>=2.0).
    - pytorch >=2.0

test:
  source_files:
    - tests
  imports:
    - shap
    - shap.cext
    - shap.explainers
    - shap.explainers.other
    - shap.explainers._deep
    - shap.plots
    - shap.plots.colors
    - shap.plots.resources
    - shap.benchmark
    - shap.maskers
    - shap.utils
    - shap.actions
    - shap.models
  commands:
    - pip check
    # OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
    # https://github.com/llvm/llvm-project/issues/54422
    - export OMP_NUM_THREADS=1  # [osx]
    - pytest -sv tests --ignore=tests/benchmark  # [not py>=313]
  requires:
    - pip
    - pytest
    - matplotlib-base
    - ipython
    - xgboost
    - pytorch  # [not win]
    - transformers  # [not win]
    # catboost py313 support started from version 1.2.8. Won`t fix.
    - catboost  # [not py>=313]
    - pyod >=1
    - lightgbm
    - sentencepiece

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations,
    uniting several previous methods and representing the only possible consistent and
    locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io
  dev_url: https://github.com/shap/shap

extra:
  recipe-maintainers:
    - connortann
    - mrandrewandrade
    - primozgodec
    - slundberg
    - xhochy
  