{% set author = "slundberg" %}
{% set name = "shap" %}
{% set version = "0.41.0" %}
{% set sha256 = "ce5117e7921f47128b529cffa0a5e7ad3f0ebcdc6d0ae57e929385bf49fb68f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  missing_dso_whitelist:  # [win]
   - $RPATH/cudart64_101.dll  # [win]
  skip: true # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - tqdm >4.25.0
    - colorama
    - slicer 0.0.7
    - numba
    - cloudpickle

test:
  requires:
    - pip
    # Numba needs NumPy 1.21 or less (according to numba itself)
    - numpy <=1.21
  commands:
    - pip check
  imports:
    - shap

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/slundberg/shap/blob/master/LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations, uniting several previous methods and representing the only possible consistent and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  doc_source_url: https://github.com/slundberg/shap/tree/master/docs
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - mrandrewandrade
    - slundberg
    - xhochy
