{% set author = "slundberg" %}
{% set name = "shap" %}
{% set version = "0.41.0" %}
{% set sha256 = "ce5117e7921f47128b529cffa0a5e7ad3f0ebcdc6d0ae57e929385bf49fb68f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  missing_dso_whitelist:  # [win]
   - $RPATH/cudart64_101.dll  # [win]
  skip: true # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
      #- make  # [unix]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy {{ numpy }}
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - tqdm >4.25.0
    - packaging >20.9
    - slicer 0.0.7
    - numba
    - cloudpickle

test:
  requires:
    - pip
    - matplotlib
  commands:
    - pip check
  imports:
    - shap
    - shap.explainers
    - shap.explainers.other
    - shap.explainers._deep
    - shap.plots
    - shap.plots.colors
    - shap.benchmark
    - shap.maskers
    - shap.utils
    - shap.actions
    - shap.models

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations, 
    uniting several previous methods and representing the only possible consistent 
    and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - mrandrewandrade
    - slundberg
    - xhochy
