{% set name = "shap" %}
{% set version = "v0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slundberg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e6b9c6203c022d3c5aa1a1fb49cd2ecd29c8398a4c329b5729529e9bca8664d7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - pandas
    - numpy
    - scikit-learn
    - scipy
    - matplotlib
    - tqdm
    - ipython
test:
  imports:
    - shap 

about:
  home: https://github.com/slundberg/shap 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A unified approach to explain the output of any machine learning model.'
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output of any machine learning model. SHAP connects game theory with local explanations, uniting several previous methods and representing the only possible consistent and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - mrandrewandrade 
    - slundberg
