{% set name = "shap" %}
{% set version = "0.50.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdc559acf7f647bc3bb22c6a1fea9f50716ed357ad595bc357b43082ae4dc6b9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - numpy {{ numpy }}
    - packaging >=20.9
    - cython >=3.0.11
  run:
    - python
    - numpy >=2
    - scipy
    - scikit-learn
    - pandas
    - tqdm >=4.27.0
    - packaging >20.9
    - slicer ==0.0.8
    - numba ==0.63.0  # [py>=314]
    - numba >=0.54  # [py<314]
    - cloudpickle
    - typing-extensions

# catboost py313 support started from version 1.2.8. Won`t fix.
{% set ignore_tests = "" %}
# On win platform:
# >       X = rng.integers(low=0, high=2, size=(n_rows, 1_100_000)).astype(np.float64)
# E       numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.4 GiB for an array with shape (2000, 1100000) and data type float64
{% set ignore_tests = " --ignore=tests/explainers/test_tree.py" %}  # [py>=313 or win]
test:
  source_files:
    - tests
  imports:
    - shap
    - shap.cext
    - shap.explainers
    - shap.explainers.other
    - shap.explainers._deep
    - shap.plots
    - shap.plots.colors
    - shap.plots.resources
    - shap.benchmark
    - shap.maskers
    - shap.utils
    - shap.actions
    - shap.models
  commands:
    - pip check
    # OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
    # https://github.com/llvm/llvm-project/issues/54422
    - export OMP_NUM_THREADS=1  # [osx]
    - pytest -sv tests {{ deselect_tests }} --ignore=tests/benchmark
  requires:
    - pip
    - pytest
    - matplotlib-base
    - ipython
    # https://github.com/shap/shap/issues/4202
    - xgboost <3.1
    - pytorch-cpu

    - transformers
    # catboost py313 support started from version 1.2.8. Won`t fix.
    - catboost  # [not py>=313]
    - pyod
    - lightgbm
    - sentencepiece

about:
  home: https://github.com/shap/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations,
    uniting several previous methods and representing the only possible consistent and
    locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io
  dev_url: https://github.com/shap/shap

extra:
  recipe-maintainers:
    - connortann
    - mrandrewandrade
    - primozgodec
    - slundberg
    - xhochy
  