{% set name = "shap" %}
{% set version = "0.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdaa5b098be5a958348015e940f6fd264339b5db1e651f9898a3117be95b05a0

build:
  number: 0
  # s390x: numba not available
  skip: true  # [py<39 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - packaging >=20.9
    - wheel
    - numpy {{ numpy }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - pandas
    - tqdm >=4.27.0
    - packaging >20.9
    - slicer ==0.0.8
    - numba
    - cloudpickle
  run_constrained:
    # scaled_dot_product_attention attribute is only available
    # with a newer version of pytorch (>=2.0).
    - pytorch >=2.0

test:
  requires:
    - pip
    - pytest
    # pytest-mpl not available
    # - pytest-mpl
    - matplotlib-base
    - ipython
    - xgboost
    # tensorflow makes pip check to fail
    # - tensorflow  # [(osx or linux64) and py<312]
    # Not available on the platforms
    - pytorch  # [not win]
    # transformers tests require pytorch
    - transformers  # [not win]
    - catboost
    # ngboost not available
    # - ngboost
    - pyod >=1
    # Fails tests/explainers/test_tree.py::test_skopt_rf_et
    # - scikit-optimize
    # Rebuild for osx-arm64?
    # - gpboost
    - lightgbm
    # Due to old pins on tensorflow, this would downgrade tensorflow massively
    # - opencv
    - sentencepiece
  source_files:
    - tests
  commands:
    - pip check
    # OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
    # https://github.com/llvm/llvm-project/issues/54422
    - export OMP_NUM_THREADS=1  # [osx]
    - pytest -sv tests --ignore=tests/benchmark
  imports:
    - shap
    - shap.cext
    - shap.explainers
    - shap.explainers.other
    - shap.explainers._deep
    - shap.plots
    - shap.plots.colors
    - shap.plots.resources
    - shap.benchmark
    - shap.maskers
    - shap.utils
    - shap.actions
    - shap.models

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations,
    uniting several previous methods and representing the only possible consistent and
    locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - connortann
    - mrandrewandrade
    - primozgodec
    - slundberg
    - xhochy
  